version: '3'

services:
  app:
    build:
      context: .
    container_name: barista_helper
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/BaristaHelper
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - 8081:8081

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=BaristaHelper
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d