version: '3.8'

services:
  app:
    image: glooomyeye/barista_helper:latest  
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/BaristaHelper
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8081:8081" 

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: BaristaHelper
    volumes:
      - pg_data:/var/lib/postgresql/data 

volumes:
  pg_data:  